server.port=8080
server.undertow.threads.io=16
server.undertow.threads.worker=200
server.undertow.request-timeout=7200000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
spring.servlet.multipart.file-size-threshold=0
spring.servlet.multipart.location=/tmp
